//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalADOdotNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int billID { get; set; }
        public string cusName { get; set; }
        public Nullable<System.DateTime> billDate { get; set; }
        public int milkID { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Milk Milk { get; set; }
    }
}
